global using Xunit;
global using Xunit.Abstractions;
global using AzureProject.Shared.Fakes;
global using AzureProject.Shared.Helpers;
global using AzureProject.Shared.Services;
global using AzureProject.Shared.Model;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Newtonsoft.Json.Linq;
