name: Nuget Tag Build
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify commit exists in branch
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/dev
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build AzureProject.Shared --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test AzureProject.Shared --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack
        run: dotnet pack AzureProject.Shared --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        run: dotnet nuget push AzureProject.Shared.${VERSION}.nupkg --source https://nuget.pkg.github.com/mdelgert/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}